version: "2"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "80:3001"
    volumes:
      - .:/deploy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
